databases:
  - name: hubdb
    plan: free
    databaseName: hub
    user: hub

services:
  - type: web
    plan: free
    name: hub
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn hub.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hubdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4